name: C++ codecov upload

on:
  - push
  - pull_request


env:
  CPP_FLAGS: --coverage -fno-inline -fno-inline-small-functions -fno-default-inline -O0 --std=c++20
  INCLUDE_FLAGS: -I ${{github.workspace}}/src/quspin_core/includes -I ${{github.workspace}}/test/test_cpp

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**","**/conda.recipe/**","**/test_cython/**","*.py","*.pyx","*.pxd"]'
          do_not_skip: '["workflow_dispatch", "schedule"]'
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download doctest
        run: wget https://github.com/doctest/doctest/releases/download/v2.4.9/doctest.h -O ${{github.workspace}}/test/test_cpp/doctest.h

      - name: Compile calculator
        working-directory: ${{github.workspace}}/test/test_cpp
        run: g++ $CPP_FLAGS $INCLUDE_FLAGS -o test test.cpp

      - name: Run tests
        working-directory: ${{github.workspace}}/test/test_cpp
        run: ./test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3          
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true
          gcov_include: test.cpp