name: C++ codecov upload

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '*.py'
      - '*.pyx'
      - '*.pxd'
      - '**/README.md'
      - '**/docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.py'
      - '*.pyx'
      - '*.pxd'
      - '**/README.md'
      - '**/docs/**'

env:
  CPP_FLAGS: --coverage -fno-inline -fno-inline-small-functions -fno-default-inline -O0
  INCLUDE_FLAGS: -I ${{github.workspace}}/src/quspin_core/includes -I ${{github.workspace}}/build/doctest/src/doctest/doctest

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Compile calculator
        working-directory: ${{github.workspace}}/test/test_cpp
        run: g++ $CPP_FLAGS $INCLUDE_FLAGS -o test test.cpp
      - name: Run tests
        run: ./test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3          
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true
          gcov_include: test.cpp