name: Cython API CI

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**/README.md'
      - '**/quspin_cpp_api/**'
      - '**/test_cpp/**'
      - '**/docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/quspin_cpp_api/**'
      - '**/test_cpp/**'
      - '**/docs/**'


jobs:
  build:
    name: ${{matrix.config.os}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macos-latest, py_version: '3.10'}
        - {os: macos-latest, py_version: '3.9'}
        - {os: macos-latest, py_version: '3.8'}
        - {os: ubuntu-latest, py_version: '3.10'}
        - {os: ubuntu-latest, py_version: '3.9'}
        - {os: ubuntu-latest, py_version: '3.8'}
        - {os: windows-latest, py_version: '3.10'}
        - {os: windows-latest, py_version: '3.9'}
        - {os: windows-latest, py_version: '3.8'}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.config.py_version}} 
    
    - name: checking pip 
      run:  python -m ensurepip --upgrade

    - name: Install
      run: pip install ${{github.workspace}}

    # - name: Test
    #   working-directory: ${{github.workspace}}/build 
    #   # Execute tests defined by the CMake configuration.
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: ctest -C ${{matrix.config.build_type}}
